<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Rudransh" failures="1" tests="1" name="AreaofTriangle_Sides_Negetive3" time="0.004" errors="0" timestamp="2021-04-02T23:02:00 CEST">
  <testcase classname="com.hcl.test.AreaOfTriangle" name="areaOfTriangle_Sides" time="0.001">
    <failure type="java.lang.AssertionError" message="Triangle is not valid">
      <![CDATA[java.lang.AssertionError: Triangle is not valid
at com.hcl.test.AreaOfTriangle.areaOfTriangle_Sides(AreaOfTriangle.java:80)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- areaOfTriangle_Sides -->
  <testcase classname="com.hcl.test.AreaOfTriangle" name="areaOfTriangle_HB" time="0.0">
    <ignored/>
  </testcase> <!-- areaOfTriangle_HB -->
</testsuite> <!-- AreaofTriangle_Sides_Negetive3 -->
